//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationWebForms.ServiceBook {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/", ConfigurationName="ServiceBook.ServiceBookSoap")]
    public interface ServiceBookSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Author", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_Author(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Author", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_AuthorAsync(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Author", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_Author(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Author", ReplyAction="*")]
        System.Threading.Tasks.Task Update_AuthorAsync(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Author", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_Author(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Author", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_AuthorAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Author", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Author();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Author", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_AuthorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Author_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApplicationWebForms.ServiceBook.Authors[] Get_Author_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Author_List", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Authors[]> Get_Author_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Authors_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Authors_Filter(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Authors_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Authors_FilterAsync(ApplicationWebForms.ServiceBook.Authors authors);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Book", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_Book(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Book", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_BookAsync(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Book", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_Book(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Book", ReplyAction="*")]
        System.Threading.Tasks.Task Update_BookAsync(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Book", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_Book(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Book", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_BookAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Book();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_BookAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApplicationWebForms.ServiceBook.Books[] Get_Book_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book_List", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Books[]> Get_Book_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Book_Filter(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Book_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Book_FilterAsync(ApplicationWebForms.ServiceBook.Books books);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_Categories(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Categories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_CategoriesAsync(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_Categories(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Categories", ReplyAction="*")]
        System.Threading.Tasks.Task Update_CategoriesAsync(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_Categories(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Categories", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_CategoriesAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Categories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Categories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Categories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_CAtegories_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApplicationWebForms.ServiceBook.Categories[] Get_CAtegories_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_CAtegories_List", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Categories[]> Get_CAtegories_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Categories_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Categories_Filter(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Categories_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Categories_FilterAsync(ApplicationWebForms.ServiceBook.Categories categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Comments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_Comments(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Comments", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_CommentsAsync(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Comments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_Comments(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Comments", ReplyAction="*")]
        System.Threading.Tasks.Task Update_CommentsAsync(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Comments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_Comments(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Comments", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_CommentsAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Comments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Comments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Comments", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_CommentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Comments_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Comments_Filter(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Comments_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Comments_FilterAsync(ApplicationWebForms.ServiceBook.Comments comments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Editorials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_Editorials(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_Editorials", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_EditorialsAsync(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Editorials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_Editorials(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_Editorials", ReplyAction="*")]
        System.Threading.Tasks.Task Update_EditorialsAsync(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Editorials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_Editorials(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_Editorials", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_EditorialsAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Editorials();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_EditorialsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApplicationWebForms.ServiceBook.Editorials[] Get_Editorials_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials_List", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Editorials[]> Get_Editorials_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Editorials_Filter(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Editorials_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Editorials_FilterAsync(ApplicationWebForms.ServiceBook.Editorials editorials);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Guid Insert_User(ApplicationWebForms.ServiceBook.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Insert_User", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Guid> Insert_UserAsync(ApplicationWebForms.ServiceBook.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update_User(ApplicationWebForms.ServiceBook.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Update_User", ReplyAction="*")]
        System.Threading.Tasks.Task Update_UserAsync(ApplicationWebForms.ServiceBook.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_User", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete_User(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Delete_User", ReplyAction="*")]
        System.Threading.Tasks.Task Delete_UserAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Users", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Users();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Users", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_UsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Users_List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ApplicationWebForms.ServiceBook.Users[] Get_Users_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_Users_List", ReplyAction="*")]
        System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Users[]> Get_Users_ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_User_Filter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_User_Filter(ApplicationWebForms.ServiceBook.Users users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nicolas_bonilla_finanzauto.net/Get_User_Filter", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_User_FilterAsync(ApplicationWebForms.ServiceBook.Users users);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Authors : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string lastnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Users : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Editorials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string nameField;
        
        private string locationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Comments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string contentField;
        
        private System.Guid user_idField;
        
        private System.Guid book_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid book_id {
            get {
                return this.book_idField;
            }
            set {
                this.book_idField = value;
                this.RaisePropertyChanged("book_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Categories : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://nicolas_bonilla_finanzauto.net/")]
    public partial class Books : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid author_idField;
        
        private System.Guid editorial_idField;
        
        private System.Guid category_idField;
        
        private string publication_yearField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid author_id {
            get {
                return this.author_idField;
            }
            set {
                this.author_idField = value;
                this.RaisePropertyChanged("author_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid editorial_id {
            get {
                return this.editorial_idField;
            }
            set {
                this.editorial_idField = value;
                this.RaisePropertyChanged("editorial_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid category_id {
            get {
                return this.category_idField;
            }
            set {
                this.category_idField = value;
                this.RaisePropertyChanged("category_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string publication_year {
            get {
                return this.publication_yearField;
            }
            set {
                this.publication_yearField = value;
                this.RaisePropertyChanged("publication_year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceBookSoapChannel : ApplicationWebForms.ServiceBook.ServiceBookSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookSoapClient : System.ServiceModel.ClientBase<ApplicationWebForms.ServiceBook.ServiceBookSoap>, ApplicationWebForms.ServiceBook.ServiceBookSoap {
        
        public ServiceBookSoapClient() {
        }
        
        public ServiceBookSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBookSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Insert_Author(ApplicationWebForms.ServiceBook.Authors authors) {
            return base.Channel.Insert_Author(authors);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_AuthorAsync(ApplicationWebForms.ServiceBook.Authors authors) {
            return base.Channel.Insert_AuthorAsync(authors);
        }
        
        public void Update_Author(ApplicationWebForms.ServiceBook.Authors authors) {
            base.Channel.Update_Author(authors);
        }
        
        public System.Threading.Tasks.Task Update_AuthorAsync(ApplicationWebForms.ServiceBook.Authors authors) {
            return base.Channel.Update_AuthorAsync(authors);
        }
        
        public void Delete_Author(System.Guid id) {
            base.Channel.Delete_Author(id);
        }
        
        public System.Threading.Tasks.Task Delete_AuthorAsync(System.Guid id) {
            return base.Channel.Delete_AuthorAsync(id);
        }
        
        public System.Data.DataSet Get_Author() {
            return base.Channel.Get_Author();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_AuthorAsync() {
            return base.Channel.Get_AuthorAsync();
        }
        
        public ApplicationWebForms.ServiceBook.Authors[] Get_Author_List() {
            return base.Channel.Get_Author_List();
        }
        
        public System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Authors[]> Get_Author_ListAsync() {
            return base.Channel.Get_Author_ListAsync();
        }
        
        public System.Data.DataSet Get_Authors_Filter(ApplicationWebForms.ServiceBook.Authors authors) {
            return base.Channel.Get_Authors_Filter(authors);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Authors_FilterAsync(ApplicationWebForms.ServiceBook.Authors authors) {
            return base.Channel.Get_Authors_FilterAsync(authors);
        }
        
        public System.Guid Insert_Book(ApplicationWebForms.ServiceBook.Books books) {
            return base.Channel.Insert_Book(books);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_BookAsync(ApplicationWebForms.ServiceBook.Books books) {
            return base.Channel.Insert_BookAsync(books);
        }
        
        public void Update_Book(ApplicationWebForms.ServiceBook.Books books) {
            base.Channel.Update_Book(books);
        }
        
        public System.Threading.Tasks.Task Update_BookAsync(ApplicationWebForms.ServiceBook.Books books) {
            return base.Channel.Update_BookAsync(books);
        }
        
        public void Delete_Book(System.Guid id) {
            base.Channel.Delete_Book(id);
        }
        
        public System.Threading.Tasks.Task Delete_BookAsync(System.Guid id) {
            return base.Channel.Delete_BookAsync(id);
        }
        
        public System.Data.DataSet Get_Book() {
            return base.Channel.Get_Book();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_BookAsync() {
            return base.Channel.Get_BookAsync();
        }
        
        public ApplicationWebForms.ServiceBook.Books[] Get_Book_List() {
            return base.Channel.Get_Book_List();
        }
        
        public System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Books[]> Get_Book_ListAsync() {
            return base.Channel.Get_Book_ListAsync();
        }
        
        public System.Data.DataSet Get_Book_Filter(ApplicationWebForms.ServiceBook.Books books) {
            return base.Channel.Get_Book_Filter(books);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Book_FilterAsync(ApplicationWebForms.ServiceBook.Books books) {
            return base.Channel.Get_Book_FilterAsync(books);
        }
        
        public System.Guid Insert_Categories(ApplicationWebForms.ServiceBook.Categories categories) {
            return base.Channel.Insert_Categories(categories);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_CategoriesAsync(ApplicationWebForms.ServiceBook.Categories categories) {
            return base.Channel.Insert_CategoriesAsync(categories);
        }
        
        public void Update_Categories(ApplicationWebForms.ServiceBook.Categories categories) {
            base.Channel.Update_Categories(categories);
        }
        
        public System.Threading.Tasks.Task Update_CategoriesAsync(ApplicationWebForms.ServiceBook.Categories categories) {
            return base.Channel.Update_CategoriesAsync(categories);
        }
        
        public void Delete_Categories(System.Guid id) {
            base.Channel.Delete_Categories(id);
        }
        
        public System.Threading.Tasks.Task Delete_CategoriesAsync(System.Guid id) {
            return base.Channel.Delete_CategoriesAsync(id);
        }
        
        public System.Data.DataSet Get_Categories() {
            return base.Channel.Get_Categories();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CategoriesAsync() {
            return base.Channel.Get_CategoriesAsync();
        }
        
        public ApplicationWebForms.ServiceBook.Categories[] Get_CAtegories_List() {
            return base.Channel.Get_CAtegories_List();
        }
        
        public System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Categories[]> Get_CAtegories_ListAsync() {
            return base.Channel.Get_CAtegories_ListAsync();
        }
        
        public System.Data.DataSet Get_Categories_Filter(ApplicationWebForms.ServiceBook.Categories categories) {
            return base.Channel.Get_Categories_Filter(categories);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Categories_FilterAsync(ApplicationWebForms.ServiceBook.Categories categories) {
            return base.Channel.Get_Categories_FilterAsync(categories);
        }
        
        public System.Guid Insert_Comments(ApplicationWebForms.ServiceBook.Comments comments) {
            return base.Channel.Insert_Comments(comments);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_CommentsAsync(ApplicationWebForms.ServiceBook.Comments comments) {
            return base.Channel.Insert_CommentsAsync(comments);
        }
        
        public void Update_Comments(ApplicationWebForms.ServiceBook.Comments comments) {
            base.Channel.Update_Comments(comments);
        }
        
        public System.Threading.Tasks.Task Update_CommentsAsync(ApplicationWebForms.ServiceBook.Comments comments) {
            return base.Channel.Update_CommentsAsync(comments);
        }
        
        public void Delete_Comments(System.Guid id) {
            base.Channel.Delete_Comments(id);
        }
        
        public System.Threading.Tasks.Task Delete_CommentsAsync(System.Guid id) {
            return base.Channel.Delete_CommentsAsync(id);
        }
        
        public System.Data.DataSet Get_Comments() {
            return base.Channel.Get_Comments();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_CommentsAsync() {
            return base.Channel.Get_CommentsAsync();
        }
        
        public System.Data.DataSet Get_Comments_Filter(ApplicationWebForms.ServiceBook.Comments comments) {
            return base.Channel.Get_Comments_Filter(comments);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Comments_FilterAsync(ApplicationWebForms.ServiceBook.Comments comments) {
            return base.Channel.Get_Comments_FilterAsync(comments);
        }
        
        public System.Guid Insert_Editorials(ApplicationWebForms.ServiceBook.Editorials editorials) {
            return base.Channel.Insert_Editorials(editorials);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_EditorialsAsync(ApplicationWebForms.ServiceBook.Editorials editorials) {
            return base.Channel.Insert_EditorialsAsync(editorials);
        }
        
        public void Update_Editorials(ApplicationWebForms.ServiceBook.Editorials editorials) {
            base.Channel.Update_Editorials(editorials);
        }
        
        public System.Threading.Tasks.Task Update_EditorialsAsync(ApplicationWebForms.ServiceBook.Editorials editorials) {
            return base.Channel.Update_EditorialsAsync(editorials);
        }
        
        public void Delete_Editorials(System.Guid id) {
            base.Channel.Delete_Editorials(id);
        }
        
        public System.Threading.Tasks.Task Delete_EditorialsAsync(System.Guid id) {
            return base.Channel.Delete_EditorialsAsync(id);
        }
        
        public System.Data.DataSet Get_Editorials() {
            return base.Channel.Get_Editorials();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_EditorialsAsync() {
            return base.Channel.Get_EditorialsAsync();
        }
        
        public ApplicationWebForms.ServiceBook.Editorials[] Get_Editorials_List() {
            return base.Channel.Get_Editorials_List();
        }
        
        public System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Editorials[]> Get_Editorials_ListAsync() {
            return base.Channel.Get_Editorials_ListAsync();
        }
        
        public System.Data.DataSet Get_Editorials_Filter(ApplicationWebForms.ServiceBook.Editorials editorials) {
            return base.Channel.Get_Editorials_Filter(editorials);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Editorials_FilterAsync(ApplicationWebForms.ServiceBook.Editorials editorials) {
            return base.Channel.Get_Editorials_FilterAsync(editorials);
        }
        
        public System.Guid Insert_User(ApplicationWebForms.ServiceBook.Users users) {
            return base.Channel.Insert_User(users);
        }
        
        public System.Threading.Tasks.Task<System.Guid> Insert_UserAsync(ApplicationWebForms.ServiceBook.Users users) {
            return base.Channel.Insert_UserAsync(users);
        }
        
        public void Update_User(ApplicationWebForms.ServiceBook.Users users) {
            base.Channel.Update_User(users);
        }
        
        public System.Threading.Tasks.Task Update_UserAsync(ApplicationWebForms.ServiceBook.Users users) {
            return base.Channel.Update_UserAsync(users);
        }
        
        public void Delete_User(System.Guid id) {
            base.Channel.Delete_User(id);
        }
        
        public System.Threading.Tasks.Task Delete_UserAsync(System.Guid id) {
            return base.Channel.Delete_UserAsync(id);
        }
        
        public System.Data.DataSet Get_Users() {
            return base.Channel.Get_Users();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_UsersAsync() {
            return base.Channel.Get_UsersAsync();
        }
        
        public ApplicationWebForms.ServiceBook.Users[] Get_Users_List() {
            return base.Channel.Get_Users_List();
        }
        
        public System.Threading.Tasks.Task<ApplicationWebForms.ServiceBook.Users[]> Get_Users_ListAsync() {
            return base.Channel.Get_Users_ListAsync();
        }
        
        public System.Data.DataSet Get_User_Filter(ApplicationWebForms.ServiceBook.Users users) {
            return base.Channel.Get_User_Filter(users);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_User_FilterAsync(ApplicationWebForms.ServiceBook.Users users) {
            return base.Channel.Get_User_FilterAsync(users);
        }
    }
}
